# Optional fixture regeneration; requires python-dateutil==2.9.0.post0.
# Normal test runs use committed literals and do not require Python.
import json
from pathlib import Path
import dateutil
from datetime import datetime, timezone, timedelta
from dateutil.rrule import rrulestr

seeds=['20240101T090000Z','20240131T090000Z','20240229T090000Z','20241230T090000Z']
patterns=[]
for interval in [1,2,7]:
 for selector in ['', 'BYDAY=MO,WE,FR', 'BYMONTHDAY=1,-1', 'BYMONTH=1,3', 'BYDAY=TU;BYMONTH=2,3']:
  patterns.append(f'FREQ=DAILY;INTERVAL={interval}'+(';' + selector if selector else ''))
for interval in [1,2,3]:
 for byday in ['', 'MO,WE,FR', 'SU,MO', 'TU,TH']:
  for wkst in ['MO','SU','SA']:
   patterns.append(f'FREQ=WEEKLY;INTERVAL={interval};WKST={wkst}'+(';BYDAY='+byday if byday else ''))
for interval in [1,2,5]:
 for selector in ['', 'BYMONTHDAY=1,-1', 'BYMONTHDAY=15,30', 'BYMONTHDAY=31', 'BYDAY=MO', 'BYDAY=2MO', 'BYDAY=-1FR', 'BYDAY=MO,TU;BYMONTHDAY=1,2,3,4,5,6,7', 'BYMONTH=2,3;BYMONTHDAY=1']:
  patterns.append(f'FREQ=MONTHLY;INTERVAL={interval}'+(';' + selector if selector else ''))
for interval in [1,2,4]:
 for selector in ['', 'BYMONTH=1,3', 'BYMONTH=2;BYMONTHDAY=29', 'BYMONTHDAY=15', 'BYMONTH=3,6;BYMONTHDAY=1,-1']:
  patterns.append(f'FREQ=YEARLY;INTERVAL={interval}'+(';' + selector if selector else ''))

assert dateutil.__version__ == '2.9.0.post0', 'Install the documented oracle version before regenerating.'
cases=[]
for index, pattern in enumerate(patterns):
 seed=datetime.strptime(seeds[index%len(seeds)],'%Y%m%dT%H%M%SZ').replace(tzinfo=timezone.utc)
 for offset in range(7):
  first=next(iter(rrulestr(pattern+';UNTIL=20320101T090000Z',dtstart=seed+timedelta(days=offset))),None)
  if first is not None:break
 assert first is not None,pattern
 for stop in ['count','until']:
  bound='COUNT=13' if stop=='count' else 'UNTIL='+(first+timedelta(days=180)).strftime('%Y%m%dT%H%M%SZ')
  rule=pattern+';'+bound
  expected=[d.strftime('%Y-%m-%dT%H:%M:%SZ') for d in rrulestr(rule,dtstart=first) if datetime(2024,1,1,tzinfo=timezone.utc)<=d<datetime(2033,1,1,tzinfo=timezone.utc)]
  cases.append({'start':first.strftime('%Y%m%dT%H%M%SZ'),'rule':rule,'expected':expected})

header='''import test from 'node:test';
import assert from 'node:assert/strict';
import { compareCalendars } from '../src/engine.js';

/** Independent, deterministic UTC golden recurrence cases.
 * Oracle: python-dateutil VERSION, dateutil.rrule.rrulestr (Python 3).
 * Generated 2026-10-03. No test-time Python or oracle dependency is required.
 * Scope: supported DAILY/WEEKLY/MONTHLY/YEARLY subset, synchronized DTSTART,
 * INTERVAL {1,2,3,4,5,7}, COUNT=13 or inclusive UNTIL 180 days after DTSTART,
 * BYMONTH/BYMONTHDAY/BYDAY intersections, ordinal monthly weekdays and WKST.
 * Excludes TZID, YEARLY BYDAY, sub-daily FREQ, BYSETPOS and undefined DTSTART.
 * Generation: select the first dateutil occurrence from one of 2024-01-01,
 * 2024-01-31, 2024-02-29, 2024-12-30 at 09:00 UTC (advance seed up to 6 days
 * if a selector makes the original rule empty through 2032). Use that first
 * occurrence as synchronized DTSTART, then expand the bounded pattern using
 * rrulestr(rule, dtstart=first). Keep starts in [2024-01-01, 2033-01-01).
 * Lists are checked in rather than regenerated by the implementation under test.
 */
const CASES = [
'''.replace('VERSION',dateutil.__version__)
rows=',\n'.join('  '+json.dumps(c,separators=(',',':')) for c in cases)
footer='''
];
const empty = 'BEGIN:VCALENDAR\\r\\nVERSION:2.0\\r\\nPRODID:-//Oracle test//EN\\r\\nEND:VCALENDAR\\r\\n';
for (const [index, fixture] of CASES.entries()) {
  test(`dateutil oracle ${index + 1}: ${fixture.start} ${fixture.rule}`, () => {
    const input = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Oracle test//EN',
      'BEGIN:VEVENT', `UID:oracle-${index}`, 'DTSTAMP:20240101T000000Z',
      `DTSTART:${fixture.start}`, 'DURATION:PT1H', `RRULE:${fixture.rule}`,
      'END:VEVENT', 'END:VCALENDAR', ''].join('\\r\\n');
    const result = compareCalendars(empty, input, { start: '2024-01-01', end: '2033-01-01' });
    assert.equal(result.complete, true, JSON.stringify(result.diagnostics));
    const actual = result.changes.map(row => row.after.start).sort();
    assert.deepEqual(actual, fixture.expected);
    assert.equal(result.summary.added, fixture.expected.length);
    assert.equal(result.summary.removed, 0);
    assert.equal(new Set(result.changes.map(row => row.id)).size, fixture.expected.length);
  });
}
'''
(Path(__file__).resolve().parents[1] / 'tests/recurrence-oracle.test.js').write_text(header+rows+footer)
print('Generated',len(cases),'independent cases;',sum(len(c['expected']) for c in cases),'golden occurrences; oracle',dateutil.__version__)
